{% if IS_DUPLICATE_SCRIPT %}
Your output script is duplicated and DID NOT CRASH THE TARGET PROGRAM.
YOU MUST ABSOLUTELY CHANGE SOMETHING IN THE SCRIPT AND TRY AGAIN, DO NOT DO THIS!

{% else %}

{% if SCRIPT_FAILED %}
The previous output was not a valid Python script! You MUST fix the Python script and try again.

This is the error message we got after running your script: 

```
{{ERROR_MSG}}
```

{% elif SINK_UNREACHABLE_FEEDBACK %}

{{SINK_UNREACHABLE_FEEDBACK}}

{% if BACKWARD_PATH %}
The previous seed successfully covered the following functions on the path towards the vulnerable function:
{{BACKWARD_PATH}}
{% endif %}

{% if FORWARD_PATH %}
However, the seed did not reach the following functions on the path towards the vulnerable function.
{{FORWARD_PATH}}
You MUST focus on reaching these functions now, and craft your next payload with the goal to achieve coverage in at least one of them! 
{% endif %}

{% if LAST_SCRIPT %}
For extra context, this is the last script you generated, please refine it!

```python
{{LAST_SCRIPT}}
```
{% endif %}

{% elif SINK_OK_NO_CRASH_FEEDBACK %}
{{SINK_OK_NO_CRASH_FEEDBACK}}

{% if LAST_SCRIPT %}
For extra context, this is the last script you generated, please refine it!
```python
{{LAST_SCRIPT}}
```
{% endif %}

{% else %}


You are given the following vulnerability report:

<--- vulnerability summary -->
Run ID: {{RUN_ID}}
Project name: {{PROJECT_NAME}}
Potential Vulnerability: {{VULN_NAME}}
Description: {{VULN_DESC}}

To successfully exploit the vulnerability, you will have to reach the function named: {{SINK_NAME}} located at {{SINK_PATH}}
This sink function seems to be reachable from the harness located at {{HARNESS_PATH}}.

The code of such harness is:
```
{{HARNESS_CODE}}
```

You MUST craft a seed to reach the sink function from the harness.

<--- exploitation suggestion -->
{{EXPL_DESC}}


{{output_format}}


{% endif %}
{% endif %}